name: GitHub Actions Version Updater

# Controls when the action will run.
on:
  schedule:
    # Automatically run on every Sunday
    - cron:  '0 0 * * 0'
  workflow_dispatch:
  push:   # Temp, for testing the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.7
        with:
          # [Required] Access token with `workflow` scope.
          token: ${{ secrets.UPDATE_ACTIONS_SECRET }}

      - name: Run GitHub Actions Version Updater
        uses: saadmk11/github-actions-version-updater@v0.8.1
        with:
          # [Required] Access token with `workflow` scope.
          token: ${{ secrets.UPDATE_ACTIONS_SECRET }}
          pull_request_user_reviewers: "michele-riva"
